export enum UAName {
  WINDOWS_PHONE = "windows-phone",
  ANDROID = "android",
  ANDROID_MOBILE = "android-mobile",
  ANDROID_TABLET = "android-tablet",
  IPAD = "iPad",
  IPHONE = "iPhone",
  IOS = "iOS",
  TABLET = "tablet",
  SMP = "smp",
  MOBILE = "mobile",
  IE9 = "ie9",
  IE10 = "ie10",
  IE11 = "ie11",
  IE = "ie",
  SAFARI = "safari",
}
